### PR TITLE
Change order of code generation in hooks

### PR DESCRIPTION
**Pull request by nvborisenko**
Execute `code`, and only then write message to output.

### CODE REVIEW

**Comment by SabotageAndi** [comment]
This change makes absolut sense. Thanks for it!

Could you please also adjust the generator for F#? https://github.com/techtalk/SpecFlow.TestProjectGenerator/blob/master/SpecFlow.TestProjectGenerator/Factories/BindingsGenerator/FSharpBindingsGenerator.cs

**Comment by nvborisenko** [comment]
Done.

**Comment by nvborisenko** [comment]
@SabotageAndi is `596b7c77-339f-42b5-9789-xxxxxxxxxxxx` your nuget api key? If no, just ignore this message.

**Comment by SabotageAndi** [comment]
@nvborisenko 	No idea, I have multiple.
Where do you find it?

**Comment by nvborisenko** [comment]
vsts nuget publish logs

**Comment by SabotageAndi** [comment]
This one?
image

No idea what this Guid is? When the NuGet task is saving the apikey to the nuget.config, it is only asteriks. 
I see this log entry in other public releases that are doing NuGet pushes, with different values.

But I reset the API key. Let's see if the guid is the same at the next push.

**Comment by SabotageAndi** [comment]
Thanks for notifying me!

**Pull request merged**
